config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :docs
  authenticated :user do
  	root "docs#index", as: "authenticated_root"
  end
  root 'welcome#index'
end

app/models/doc.rb
class Doc < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
	before_action :find_doc, only: [:show, :edit, :update, :destroy]

	def index
		@docs = Doc.where(user_id: current_user) 
	end

	def show
	end

	def new
		@doc = current_user.docs.build
	end

	def create
		@doc = current_user.docs.build(doc_params)

		if @doc.save
			redirect_to @doc
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @doc.update(doc_params)
			redirect_to @doc 
		else
			render 'edit'
		end
	end

	def destroy
		@doc.destroy
		redirect_to docs_path
	end

	private

		def find_doc
			@doc = Doc.find(params[:id])
		end

		def doc_params
			params.require(:doc).permit(:title, :content)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
	= f.input :title
	= f.input :content
	= f.button :submit

app/views/docs/edit.html.haml
%h1 Edit Doc

= render 'form' 
= link_to "Cancel", doc_path, class: "abort"

app/views/docs/index.html.haml
%div
	-unless @docs.blank?
		- @docs.each do |doc|
			.files
				%h2= doc.title
				%p= "created " + time_ago_in_words(doc.created_at) + " ago"
				%p= truncate(doc.content, length:50)
				%p= link_to "View Doc", doc, class: "view_doc"
	- else
		%h2 Create Doc!

app/views/docs/new.html.haml
.form_wrapper
	%h1 Create Doc

	= render 'form'
	= link_to "Cancel", docs_path, class: "abort"

app/views/docs/show.html.haml
.file_show
	%h1= @doc.title
	%p= simple_format(@doc.content)
	%hr

= link_to "All Docs", docs_path, id: "docs_btn"
= link_to "Edit", edit_doc_path(@doc), id: "docs_edit_btn"
= link_to "Delete", doc_path(@doc), method: :delete, data: { confirm: "Are you sure?" }, id: "docs_delete_btn"

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Qrolet
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%header
		.header_inner
			= link_to "Qrolet", root_path, id: "logo"

			%nav
				- if user_signed_in?
					= link_to "Create Doc", new_doc_path, id: "createdoc_btn"
					= link_to "Sign Out", destroy_user_session_path, method: :delete, id: "logout_btn"
				- else
					= link_to "Login", new_user_session_path, id: "login_btn"
					= link_to "Sign Up", new_user_registration_path, id: "register_btn"
	%p.notice= notice
	%p.alert= alert

	.container
		= yield 

app/views/welcome/index.html.haml
.hero
	%h1 Document your thoughts and ideas.
	%p Thoughts pop up without notification. Cabinet lets you capture, nurture, and share your ideas across any device. Store once, accessible everywhere.